# CAPSTONE PROJEKT - Gruppe D
Notebook 1: Business Understanding und Data Understanding

Wir folgen bewusst dem CRISP-DM-Prozess:

1. Business Understanding
2. Data Understanding
3. Data Preparation
4. Modeling
5. Evaluation
6. Deployment / Interpretation

## 1. Business Understanding

Genaue Prognosen von Goldpreisen helfen Investoren, Finanzinstituten und Rohstoffhändlern dabei, Kauf-, Halte- oder Verkaufsentscheidungen zu treffen. Sie unterstützen zudem die Portfolioallokation, das Risikomanagement und Absicherungsstrategien (Hedging).

Stakeholder (Interessengruppen):
- Investoren 
- Banken 
- Rohstoffhändler 
- Portfolio-Manager

## 2. Data Understanding
In diesem Kapitel wird untersucht ob die Daten fehlende Werte enthalten.

In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

# Gold Futures Ticker laden
gold = yf.Ticker("GC=F")

# Alle verfügbaren Daten in Tagesschritten abrufen
df = gold.history(start="2000-09-01", interval="1d")

# Die prozentuale Veränderung zum Vortag berechnen
df['Change %'] = df['Close'].pct_change()

# Spalten auswählen
spaltenname = df.columns.tolist()
print('Spaltenname prüfen' , spaltenname)

#df = df[['Close', 'Open', 'High', 'Low', 'Volume', 'Change %']]


# Die Daten als CSV-Datei speichern
#df.to_csv("../Data/goldpreis_seit_2000.csv")

# print(df.tail())
#Vermutung: Datum ist ein Index
print(df['Open'].head())

Spaltenname prüfen ['Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits', 'Change %']
Date
2000-09-01 00:00:00-04:00    277.000000
2000-09-05 00:00:00-04:00    275.799988
2000-09-06 00:00:00-04:00    274.200012
2000-09-07 00:00:00-04:00    274.000000
2000-09-08 00:00:00-04:00    273.299988
Name: Open, dtype: float64

In [2]:
# Die Daten als CSV-Datei speichern
df.to_csv("../Data/goldpreis_seit_2000.csv")

In [3]:
df.size

51888

In [4]:
#Vermutung: Datum ist ein Index
df.index

#Ergebnis: Datum ist aktuell ein Index.

DatetimeIndex(['2000-09-01 00:00:00-04:00', '2000-09-05 00:00:00-04:00',
               '2000-09-06 00:00:00-04:00', '2000-09-07 00:00:00-04:00',
               '2000-09-08 00:00:00-04:00', '2000-09-11 00:00:00-04:00',
               '2000-09-12 00:00:00-04:00', '2000-09-13 00:00:00-04:00',
               '2000-09-14 00:00:00-04:00', '2000-09-15 00:00:00-04:00',
               ...
               '2026-06-26 00:00:00-04:00', '2026-06-29 00:00:00-04:00',
               '2026-06-30 00:00:00-04:00', '2026-07-01 00:00:00-04:00',
               '2026-07-02 00:00:00-04:00', '2026-07-06 00:00:00-04:00',
               '2026-07-07 00:00:00-04:00', '2026-07-08 00:00:00-04:00',
               '2026-07-09 00:00:00-04:00', '2026-07-10 00:00:00-04:00'],
              dtype='datetime64[s, America/New_York]', name='Date', length=6486, freq=None)

In [5]:
# Index droppen:
df_prep = df.reset_index()

In [6]:
spaltenname2 = df_prep.columns.tolist()
print(spaltenname2)

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits', 'Change %']

In [7]:
# Die Daten als CSV-Datei speichern
#df.to_csv("../Data/goldpreis_seit_2000.csv")

print(df_prep.tail())

                          Date         Open         High          Low  \
6481 2026-07-06 00:00:00-04:00  4175.399902  4199.700195  4134.200195
6482 2026-07-07 00:00:00-04:00  4126.500000  4167.200195  4107.200195
6483 2026-07-08 00:00:00-04:00  4116.299805  4120.299805  4053.000000
6484 2026-07-09 00:00:00-04:00  4066.399902  4130.600098  4064.199951
6485 2026-07-10 00:00:00-04:00  4135.399902  4144.600098  4081.699951

            Close  Volume  Dividends  Stock Splits  Change %
6481  4155.100098    1024        0.0           0.0  0.010310
6482  4145.299805      53        0.0           0.0 -0.002359
6483  4070.899902     292        0.0           0.0 -0.017948
6484  4130.600098      13        0.0           0.0  0.014665
6485  4113.700195   91801        0.0           0.0 -0.004091

In [8]:
# Uhrzeit aus Datumsfeld entfernen
df_prep['Date'] = pd.to_datetime(df_prep['Date'],format="%Y-%m-%d")

In [9]:
# Check
df_prep['Date']

0      2000-09-01 00:00:00-04:00
1      2000-09-05 00:00:00-04:00
2      2000-09-06 00:00:00-04:00
3      2000-09-07 00:00:00-04:00
4      2000-09-08 00:00:00-04:00
                  ...
6481   2026-07-06 00:00:00-04:00
6482   2026-07-07 00:00:00-04:00
6483   2026-07-08 00:00:00-04:00
6484   2026-07-09 00:00:00-04:00
6485   2026-07-10 00:00:00-04:00
Name: Date, Length: 6486, dtype: datetime64[s, America/New_York]

In [10]:
print(df_prep['Date'].dtype)

datetime64[s, America/New_York]

In [11]:
#Anzahl fehlende Werte pro Spalte
df_prep.isna().sum()

Date            0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
Change %        1
dtype: int64

In [12]:
# Prüfe wo im Datensatz leere Wert verhanden sind
zeilen, spalten = np.where(df_prep.isna())

for z, s in zip(zeilen, spalten):
    print(f"Leere Zelle gefunden in Zeile: {df_prep.index[z]} | Spalte: {df_prep.columns[s]}")

Leere Zelle gefunden in Zeile: 0 | Spalte: Change %

In [13]:
# Leerzeichen prüfen
maske_leerzeichen = df_prep.map(lambda x: isinstance(x, str) and x.strip() == '' and len(x) > 0)

# Koordinaten (Zeile und Spalte) auslesen
zeilen, spalten = np.where(maske_leerzeichen)

for z, s in zip(zeilen, spalten):
    print(f"Reines Leerzeichen gefunden -> Zeile: {df_prep.index[z]} | Spalte: {df_prep.columns[s]}")

In [14]:
df_prep.fillna(0.0, inplace=True)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Change %
0,2000-09-01 00:00:00-04:00,277.000000,277.000000,277.000000,277.000000,0,0.0,0.0,0.000000
1,2000-09-05 00:00:00-04:00,275.799988,275.799988,275.799988,275.799988,2,0.0,0.0,-0.004332
2,2000-09-06 00:00:00-04:00,274.200012,274.200012,274.200012,274.200012,0,0.0,0.0,-0.005801
3,2000-09-07 00:00:00-04:00,274.000000,274.000000,274.000000,274.000000,125,0.0,0.0,-0.000729
4,2000-09-08 00:00:00-04:00,273.299988,273.299988,273.299988,273.299988,0,0.0,0.0,-0.002555
...,...,...,...,...,...,...,...,...,...
6481,2026-07-06 00:00:00-04:00,4175.399902,4199.700195,4134.200195,4155.100098,1024,0.0,0.0,0.010310
6482,2026-07-07 00:00:00-04:00,4126.500000,4167.200195,4107.200195,4145.299805,53,0.0,0.0,-0.002359
6483,2026-07-08 00:00:00-04:00,4116.299805,4120.299805,4053.000000,4070.899902,292,0.0,0.0,-0.017948
6484,2026-07-09 00:00:00-04:00,4066.399902,4130.600098,4064.199951,4130.600098,13,0.0,0.0,0.014665
6485,2026-07-10 00:00:00-04:00,4135.399902,4144.600098,4081.699951,4113.700195,91801,0.0,0.0,-0.004091

In [15]:
# Check: Spalten
spaltenname = df_prep.columns.tolist()
print(spaltenname)

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Dividends', 'Stock Splits', 'Change %']

In [16]:
spaltenanzahl = df_prep.columns.size
print(spaltenanzahl)

9

In [17]:
sizedf = df_prep.size
print(sizedf)

58374

In [18]:
df_prep.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Change %
0,2000-09-01 00:00:00-04:00,277.000000,277.000000,277.000000,277.000000,0,0.0,0.0,0.000000
1,2000-09-05 00:00:00-04:00,275.799988,275.799988,275.799988,275.799988,2,0.0,0.0,-0.004332
2,2000-09-06 00:00:00-04:00,274.200012,274.200012,274.200012,274.200012,0,0.0,0.0,-0.005801
3,2000-09-07 00:00:00-04:00,274.000000,274.000000,274.000000,274.000000,125,0.0,0.0,-0.000729
4,2000-09-08 00:00:00-04:00,273.299988,273.299988,273.299988,273.299988,0,0.0,0.0,-0.002555

In [30]:
referenz_kalender = pd.DataFrame({'Date': pd.date_range(start="2000-09-01", end="2026-07-12", freq="D")})
referenz_kalender.head()

        Date
0 2000-09-01
1 2000-09-02
2 2000-09-03
3 2000-09-04
4 2000-09-05

In [ ]:
import pandas as pd

dates_ref = pd.to_datetime(referenz_kalender['Date'], utc=True, errors='coerce')
dates_dat = pd.to_datetime(df_prep['Date'], utc=True, errors='coerce')


set_referenz = set(dates_ref.dt.date.dropna())
set_daten = set(dates_dat.dt.date.dropna())

fehlende_tage_liste = sorted(list(set_referenz - set_daten))

# 4. Ergebnis zurück in ein sauberes DataFrame gießen
fehlende_tage_df = pd.DataFrame({'Datum': pd.to_datetime(fehlende_tage_liste)})

print("\nDie ersten fehlenden Tage:")
print(fehlende_tage_df.head(10))
print(fehlende_tage_df.size)

Anzahl fehlender Tage: 2960

Die ersten fehlenden Tage:
       Datum
0 2000-09-02
1 2000-09-03
2 2000-09-04
3 2000-09-09
4 2000-09-10
5 2000-09-16
6 2000-09-17
7 2000-09-23
8 2000-09-24
9 2000-09-30
2960

In [33]:
# Ergebnis: Uns fehlen 2960 Tage in den Quelldaten bezogen auf einen Kalendervergleich
# Check wie viele Tage davon Wochenende und Feiertage sind:
import holidays
#print(holidays.list_supported_countries())

from datetime import date
import holidays
jahre_int = list(range(2000, 2027))
liste_feiertage = []
for y in jahre_int:
    for h in holidays.US(years=y).items():
        #print(h)
        liste_feiertage.append(h)
        

print(liste_feiertage)
feiertag_df = pd.DataFrame(liste_feiertage, columns=["Datum","Name des Feiertags"])
print(feiertag_df.head())

[(datetime.date(2000, 1, 1), "New Year's Day"), (datetime.date(2000, 5, 29), 'Memorial Day'), (datetime.date(2000, 7, 4), 'Independence Day'), (datetime.date(2000, 9, 4), 'Labor Day'), (datetime.date(2000, 11, 23), 'Thanksgiving Day'), (datetime.date(2000, 12, 25), 'Christmas Day'), (datetime.date(2000, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2000, 2, 21), "Washington's Birthday"), (datetime.date(2000, 10, 9), 'Columbus Day'), (datetime.date(2000, 11, 11), 'Veterans Day'), (datetime.date(2000, 11, 10), 'Veterans Day (observed)'), (datetime.date(2001, 1, 1), "New Year's Day"), (datetime.date(2001, 5, 28), 'Memorial Day'), (datetime.date(2001, 7, 4), 'Independence Day'), (datetime.date(2001, 9, 3), 'Labor Day'), (datetime.date(2001, 11, 22), 'Thanksgiving Day'), (datetime.date(2001, 12, 25), 'Christmas Day'), (datetime.date(2001, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2001, 2, 19), "Washington's Birthday"), (datetime.date(2001, 10, 8), 'Columbus Day'), (datetime.date(2001, 11, 11), 'Veterans Day'), (datetime.date(2001, 11, 12), 'Veterans Day (observed)'), (datetime.date(2002, 1, 1), "New Year's Day"), (datetime.date(2002, 5, 27), 'Memorial Day'), (datetime.date(2002, 7, 4), 'Independence Day'), (datetime.date(2002, 9, 2), 'Labor Day'), (datetime.date(2002, 11, 28), 'Thanksgiving Day'), (datetime.date(2002, 12, 25), 'Christmas Day'), (datetime.date(2002, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2002, 2, 18), "Washington's Birthday"), (datetime.date(2002, 10, 14), 'Columbus Day'), (datetime.date(2002, 11, 11), 'Veterans Day'), (datetime.date(2003, 1, 1), "New Year's Day"), (datetime.date(2003, 5, 26), 'Memorial Day'), (datetime.date(2003, 7, 4), 'Independence Day'), (datetime.date(2003, 9, 1), 'Labor Day'), (datetime.date(2003, 11, 27), 'Thanksgiving Day'), (datetime.date(2003, 12, 25), 'Christmas Day'), (datetime.date(2003, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2003, 2, 17), "Washington's Birthday"), (datetime.date(2003, 10, 13), 'Columbus Day'), (datetime.date(2003, 11, 11), 'Veterans Day'), (datetime.date(2004, 1, 1), "New Year's Day"), (datetime.date(2004, 12, 31), "New Year's Day (observed)"), (datetime.date(2004, 5, 31), 'Memorial Day'), (datetime.date(2004, 7, 4), 'Independence Day'), (datetime.date(2004, 7, 5), 'Independence Day (observed)'), (datetime.date(2004, 9, 6), 'Labor Day'), (datetime.date(2004, 11, 25), 'Thanksgiving Day'), (datetime.date(2004, 12, 25), 'Christmas Day'), (datetime.date(2004, 12, 24), 'Christmas Day (observed)'), (datetime.date(2004, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2004, 2, 16), "Washington's Birthday"), (datetime.date(2004, 10, 11), 'Columbus Day'), (datetime.date(2004, 11, 11), 'Veterans Day'), (datetime.date(2005, 1, 1), "New Year's Day"), (datetime.date(2005, 5, 30), 'Memorial Day'), (datetime.date(2005, 7, 4), 'Independence Day'), (datetime.date(2005, 9, 5), 'Labor Day'), (datetime.date(2005, 11, 24), 'Thanksgiving Day'), (datetime.date(2005, 12, 25), 'Christmas Day'), (datetime.date(2005, 12, 26), 'Christmas Day (observed)'), (datetime.date(2005, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2005, 2, 21), "Washington's Birthday"), (datetime.date(2005, 10, 10), 'Columbus Day'), (datetime.date(2005, 11, 11), 'Veterans Day'), (datetime.date(2006, 1, 1), "New Year's Day"), (datetime.date(2006, 1, 2), "New Year's Day (observed)"), (datetime.date(2006, 5, 29), 'Memorial Day'), (datetime.date(2006, 7, 4), 'Independence Day'), (datetime.date(2006, 9, 4), 'Labor Day'), (datetime.date(2006, 11, 23), 'Thanksgiving Day'), (datetime.date(2006, 12, 25), 'Christmas Day'), (datetime.date(2006, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2006, 2, 20), "Washington's Birthday"), (datetime.date(2006, 10, 9), 'Columbus Day'), (datetime.date(2006, 11, 11), 'Veterans Day'), (datetime.date(2006, 11, 10), 'Veterans Day (observed)'), (datetime.date(2007, 1, 1), "New Year's Day"), (datetime.date(2007, 5, 28), 'Memorial Day'), (datetime.date(2007, 7, 4), 'Independence Day'), (datetime.date(2007, 9, 3), 'Labor Day'), (datetime.date(2007, 11, 22), 'Thanksgiving Day'), (datetime.date(2007, 12, 25), 'Christmas Day'), (datetime.date(2007, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2007, 2, 19), "Washington's Birthday"), (datetime.date(2007, 10, 8), 'Columbus Day'), (datetime.date(2007, 11, 11), 'Veterans Day'), (datetime.date(2007, 11, 12), 'Veterans Day (observed)'), (datetime.date(2008, 1, 1), "New Year's Day"), (datetime.date(2008, 5, 26), 'Memorial Day'), (datetime.date(2008, 7, 4), 'Independence Day'), (datetime.date(2008, 9, 1), 'Labor Day'), (datetime.date(2008, 11, 27), 'Thanksgiving Day'), (datetime.date(2008, 12, 25), 'Christmas Day'), (datetime.date(2008, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2008, 2, 18), "Washington's Birthday"), (datetime.date(2008, 10, 13), 'Columbus Day'), (datetime.date(2008, 11, 11), 'Veterans Day'), (datetime.date(2009, 1, 1), "New Year's Day"), (datetime.date(2009, 5, 25), 'Memorial Day'), (datetime.date(2009, 7, 4), 'Independence Day'), (datetime.date(2009, 7, 3), 'Independence Day (observed)'), (datetime.date(2009, 9, 7), 'Labor Day'), (datetime.date(2009, 11, 26), 'Thanksgiving Day'), (datetime.date(2009, 12, 25), 'Christmas Day'), (datetime.date(2009, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2009, 2, 16), "Washington's Birthday"), (datetime.date(2009, 10, 12), 'Columbus Day'), (datetime.date(2009, 11, 11), 'Veterans Day'), (datetime.date(2010, 1, 1), "New Year's Day"), (datetime.date(2010, 12, 31), "New Year's Day (observed)"), (datetime.date(2010, 5, 31), 'Memorial Day'), (datetime.date(2010, 7, 4), 'Independence Day'), (datetime.date(2010, 7, 5), 'Independence Day (observed)'), (datetime.date(2010, 9, 6), 'Labor Day'), (datetime.date(2010, 11, 25), 'Thanksgiving Day'), (datetime.date(2010, 12, 25), 'Christmas Day'), (datetime.date(2010, 12, 24), 'Christmas Day (observed)'), (datetime.date(2010, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2010, 2, 15), "Washington's Birthday"), (datetime.date(2010, 10, 11), 'Columbus Day'), (datetime.date(2010, 11, 11), 'Veterans Day'), (datetime.date(2011, 1, 1), "New Year's Day"), (datetime.date(2011, 5, 30), 'Memorial Day'), (datetime.date(2011, 7, 4), 'Independence Day'), (datetime.date(2011, 9, 5), 'Labor Day'), (datetime.date(2011, 11, 24), 'Thanksgiving Day'), (datetime.date(2011, 12, 25), 'Christmas Day'), (datetime.date(2011, 12, 26), 'Christmas Day (observed)'), (datetime.date(2011, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2011, 2, 21), "Washington's Birthday"), (datetime.date(2011, 10, 10), 'Columbus Day'), (datetime.date(2011, 11, 11), 'Veterans Day'), (datetime.date(2012, 1, 1), "New Year's Day"), (datetime.date(2012, 1, 2), "New Year's Day (observed)"), (datetime.date(2012, 5, 28), 'Memorial Day'), (datetime.date(2012, 7, 4), 'Independence Day'), (datetime.date(2012, 9, 3), 'Labor Day'), (datetime.date(2012, 11, 22), 'Thanksgiving Day'), (datetime.date(2012, 12, 25), 'Christmas Day'), (datetime.date(2012, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2012, 2, 20), "Washington's Birthday"), (datetime.date(2012, 10, 8), 'Columbus Day'), (datetime.date(2012, 11, 11), 'Veterans Day'), (datetime.date(2012, 11, 12), 'Veterans Day (observed)'), (datetime.date(2013, 1, 1), "New Year's Day"), (datetime.date(2013, 5, 27), 'Memorial Day'), (datetime.date(2013, 7, 4), 'Independence Day'), (datetime.date(2013, 9, 2), 'Labor Day'), (datetime.date(2013, 11, 28), 'Thanksgiving Day'), (datetime.date(2013, 12, 25), 'Christmas Day'), (datetime.date(2013, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2013, 2, 18), "Washington's Birthday"), (datetime.date(2013, 10, 14), 'Columbus Day'), (datetime.date(2013, 11, 11), 'Veterans Day'), (datetime.date(2014, 1, 1), "New Year's Day"), (datetime.date(2014, 5, 26), 'Memorial Day'), (datetime.date(2014, 7, 4), 'Independence Day'), (datetime.date(2014, 9, 1), 'Labor Day'), (datetime.date(2014, 11, 27), 'Thanksgiving Day'), (datetime.date(2014, 12, 25), 'Christmas Day'), (datetime.date(2014, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2014, 2, 17), "Washington's Birthday"), (datetime.date(2014, 10, 13), 'Columbus Day'), (datetime.date(2014, 11, 11), 'Veterans Day'), (datetime.date(2015, 1, 1), "New Year's Day"), (datetime.date(2015, 5, 25), 'Memorial Day'), (datetime.date(2015, 7, 4), 'Independence Day'), (datetime.date(2015, 7, 3), 'Independence Day (observed)'), (datetime.date(2015, 9, 7), 'Labor Day'), (datetime.date(2015, 11, 26), 'Thanksgiving Day'), (datetime.date(2015, 12, 25), 'Christmas Day'), (datetime.date(2015, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2015, 2, 16), "Washington's Birthday"), (datetime.date(2015, 10, 12), 'Columbus Day'), (datetime.date(2015, 11, 11), 'Veterans Day'), (datetime.date(2016, 1, 1), "New Year's Day"), (datetime.date(2016, 5, 30), 'Memorial Day'), (datetime.date(2016, 7, 4), 'Independence Day'), (datetime.date(2016, 9, 5), 'Labor Day'), (datetime.date(2016, 11, 24), 'Thanksgiving Day'), (datetime.date(2016, 12, 25), 'Christmas Day'), (datetime.date(2016, 12, 26), 'Christmas Day (observed)'), (datetime.date(2016, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2016, 2, 15), "Washington's Birthday"), (datetime.date(2016, 10, 10), 'Columbus Day'), (datetime.date(2016, 11, 11), 'Veterans Day'), (datetime.date(2017, 1, 1), "New Year's Day"), (datetime.date(2017, 1, 2), "New Year's Day (observed)"), (datetime.date(2017, 5, 29), 'Memorial Day'), (datetime.date(2017, 7, 4), 'Independence Day'), (datetime.date(2017, 9, 4), 'Labor Day'), (datetime.date(2017, 11, 23), 'Thanksgiving Day'), (datetime.date(2017, 12, 25), 'Christmas Day'), (datetime.date(2017, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2017, 2, 20), "Washington's Birthday"), (datetime.date(2017, 10, 9), 'Columbus Day'), (datetime.date(2017, 11, 11), 'Veterans Day'), (datetime.date(2017, 11, 10), 'Veterans Day (observed)'), (datetime.date(2018, 1, 1), "New Year's Day"), (datetime.date(2018, 5, 28), 'Memorial Day'), (datetime.date(2018, 7, 4), 'Independence Day'), (datetime.date(2018, 9, 3), 'Labor Day'), (datetime.date(2018, 11, 22), 'Thanksgiving Day'), (datetime.date(2018, 12, 25), 'Christmas Day'), (datetime.date(2018, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2018, 2, 19), "Washington's Birthday"), (datetime.date(2018, 10, 8), 'Columbus Day'), (datetime.date(2018, 11, 11), 'Veterans Day'), (datetime.date(2018, 11, 12), 'Veterans Day (observed)'), (datetime.date(2019, 1, 1), "New Year's Day"), (datetime.date(2019, 5, 27), 'Memorial Day'), (datetime.date(2019, 7, 4), 'Independence Day'), (datetime.date(2019, 9, 2), 'Labor Day'), (datetime.date(2019, 11, 28), 'Thanksgiving Day'), (datetime.date(2019, 12, 25), 'Christmas Day'), (datetime.date(2019, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2019, 2, 18), "Washington's Birthday"), (datetime.date(2019, 10, 14), 'Columbus Day'), (datetime.date(2019, 11, 11), 'Veterans Day'), (datetime.date(2020, 1, 1), "New Year's Day"), (datetime.date(2020, 5, 25), 'Memorial Day'), (datetime.date(2020, 7, 4), 'Independence Day'), (datetime.date(2020, 7, 3), 'Independence Day (observed)'), (datetime.date(2020, 9, 7), 'Labor Day'), (datetime.date(2020, 11, 26), 'Thanksgiving Day'), (datetime.date(2020, 12, 25), 'Christmas Day'), (datetime.date(2020, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2020, 2, 17), "Washington's Birthday"), (datetime.date(2020, 10, 12), 'Columbus Day'), (datetime.date(2020, 11, 11), 'Veterans Day'), (datetime.date(2021, 1, 1), "New Year's Day"), (datetime.date(2021, 12, 31), "New Year's Day (observed)"), (datetime.date(2021, 5, 31), 'Memorial Day'), (datetime.date(2021, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2021, 6, 18), 'Juneteenth National Independence Day (observed)'), (datetime.date(2021, 7, 4), 'Independence Day'), (datetime.date(2021, 7, 5), 'Independence Day (observed)'), (datetime.date(2021, 9, 6), 'Labor Day'), (datetime.date(2021, 11, 25), 'Thanksgiving Day'), (datetime.date(2021, 12, 25), 'Christmas Day'), (datetime.date(2021, 12, 24), 'Christmas Day (observed)'), (datetime.date(2021, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2021, 2, 15), "Washington's Birthday"), (datetime.date(2021, 10, 11), 'Columbus Day'), (datetime.date(2021, 11, 11), 'Veterans Day'), (datetime.date(2022, 1, 1), "New Year's Day"), (datetime.date(2022, 5, 30), 'Memorial Day'), (datetime.date(2022, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2022, 6, 20), 'Juneteenth National Independence Day (observed)'), (datetime.date(2022, 7, 4), 'Independence Day'), (datetime.date(2022, 9, 5), 'Labor Day'), (datetime.date(2022, 11, 24), 'Thanksgiving Day'), (datetime.date(2022, 12, 25), 'Christmas Day'), (datetime.date(2022, 12, 26), 'Christmas Day (observed)'), (datetime.date(2022, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2022, 2, 21), "Washington's Birthday"), (datetime.date(2022, 10, 10), 'Columbus Day'), (datetime.date(2022, 11, 11), 'Veterans Day'), (datetime.date(2023, 1, 1), "New Year's Day"), (datetime.date(2023, 1, 2), "New Year's Day (observed)"), (datetime.date(2023, 5, 29), 'Memorial Day'), (datetime.date(2023, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2023, 7, 4), 'Independence Day'), (datetime.date(2023, 9, 4), 'Labor Day'), (datetime.date(2023, 11, 23), 'Thanksgiving Day'), (datetime.date(2023, 12, 25), 'Christmas Day'), (datetime.date(2023, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2023, 2, 20), "Washington's Birthday"), (datetime.date(2023, 10, 9), 'Columbus Day'), (datetime.date(2023, 11, 11), 'Veterans Day'), (datetime.date(2023, 11, 10), 'Veterans Day (observed)'), (datetime.date(2024, 1, 1), "New Year's Day"), (datetime.date(2024, 5, 27), 'Memorial Day'), (datetime.date(2024, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2024, 7, 4), 'Independence Day'), (datetime.date(2024, 9, 2), 'Labor Day'), (datetime.date(2024, 11, 28), 'Thanksgiving Day'), (datetime.date(2024, 12, 25), 'Christmas Day'), (datetime.date(2024, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2024, 2, 19), "Washington's Birthday"), (datetime.date(2024, 10, 14), 'Columbus Day'), (datetime.date(2024, 11, 11), 'Veterans Day'), (datetime.date(2025, 1, 1), "New Year's Day"), (datetime.date(2025, 5, 26), 'Memorial Day'), (datetime.date(2025, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2025, 7, 4), 'Independence Day'), (datetime.date(2025, 9, 1), 'Labor Day'), (datetime.date(2025, 11, 27), 'Thanksgiving Day'), (datetime.date(2025, 12, 25), 'Christmas Day'), (datetime.date(2025, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2025, 2, 17), "Washington's Birthday"), (datetime.date(2025, 10, 13), 'Columbus Day'), (datetime.date(2025, 11, 11), 'Veterans Day'), (datetime.date(2026, 1, 1), "New Year's Day"), (datetime.date(2026, 5, 25), 'Memorial Day'), (datetime.date(2026, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2026, 7, 4), 'Independence Day'), (datetime.date(2026, 7, 3), 'Independence Day (observed)'), (datetime.date(2026, 9, 7), 'Labor Day'), (datetime.date(2026, 11, 26), 'Thanksgiving Day'), (datetime.date(2026, 12, 25), 'Christmas Day'), (datetime.date(2026, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2026, 2, 16), "Washington's Birthday"), (datetime.date(2026, 10, 12), 'Columbus Day'), (datetime.date(2026, 11, 11), 'Veterans Day')]
        Datum Name des Feiertags
0  2000-01-01     New Year's Day
1  2000-05-29       Memorial Day
2  2000-07-04   Independence Day
3  2000-09-04          Labor Day
4  2000-11-23   Thanksgiving Day

In [34]:
from datetime import datetime
start="2000-09-01"
ende="2026-07-12"
soll_kalender = pd.date_range(start=start, end=ende, freq="D")
soll_kalender_lst = soll_kalender.tolist()
liste_we = []
for d in soll_kalender_lst:
    # Samstag prüfen (5)
    if d.weekday() == 5:
        liste_we.append(d)
    if d.weekday() == 6:
        liste_we.append(d)

print(liste_feiertage)
we_df = pd.DataFrame(liste_we, columns=["Datum"])
print(we_df.head())

[(datetime.date(2000, 1, 1), "New Year's Day"), (datetime.date(2000, 5, 29), 'Memorial Day'), (datetime.date(2000, 7, 4), 'Independence Day'), (datetime.date(2000, 9, 4), 'Labor Day'), (datetime.date(2000, 11, 23), 'Thanksgiving Day'), (datetime.date(2000, 12, 25), 'Christmas Day'), (datetime.date(2000, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2000, 2, 21), "Washington's Birthday"), (datetime.date(2000, 10, 9), 'Columbus Day'), (datetime.date(2000, 11, 11), 'Veterans Day'), (datetime.date(2000, 11, 10), 'Veterans Day (observed)'), (datetime.date(2001, 1, 1), "New Year's Day"), (datetime.date(2001, 5, 28), 'Memorial Day'), (datetime.date(2001, 7, 4), 'Independence Day'), (datetime.date(2001, 9, 3), 'Labor Day'), (datetime.date(2001, 11, 22), 'Thanksgiving Day'), (datetime.date(2001, 12, 25), 'Christmas Day'), (datetime.date(2001, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2001, 2, 19), "Washington's Birthday"), (datetime.date(2001, 10, 8), 'Columbus Day'), (datetime.date(2001, 11, 11), 'Veterans Day'), (datetime.date(2001, 11, 12), 'Veterans Day (observed)'), (datetime.date(2002, 1, 1), "New Year's Day"), (datetime.date(2002, 5, 27), 'Memorial Day'), (datetime.date(2002, 7, 4), 'Independence Day'), (datetime.date(2002, 9, 2), 'Labor Day'), (datetime.date(2002, 11, 28), 'Thanksgiving Day'), (datetime.date(2002, 12, 25), 'Christmas Day'), (datetime.date(2002, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2002, 2, 18), "Washington's Birthday"), (datetime.date(2002, 10, 14), 'Columbus Day'), (datetime.date(2002, 11, 11), 'Veterans Day'), (datetime.date(2003, 1, 1), "New Year's Day"), (datetime.date(2003, 5, 26), 'Memorial Day'), (datetime.date(2003, 7, 4), 'Independence Day'), (datetime.date(2003, 9, 1), 'Labor Day'), (datetime.date(2003, 11, 27), 'Thanksgiving Day'), (datetime.date(2003, 12, 25), 'Christmas Day'), (datetime.date(2003, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2003, 2, 17), "Washington's Birthday"), (datetime.date(2003, 10, 13), 'Columbus Day'), (datetime.date(2003, 11, 11), 'Veterans Day'), (datetime.date(2004, 1, 1), "New Year's Day"), (datetime.date(2004, 12, 31), "New Year's Day (observed)"), (datetime.date(2004, 5, 31), 'Memorial Day'), (datetime.date(2004, 7, 4), 'Independence Day'), (datetime.date(2004, 7, 5), 'Independence Day (observed)'), (datetime.date(2004, 9, 6), 'Labor Day'), (datetime.date(2004, 11, 25), 'Thanksgiving Day'), (datetime.date(2004, 12, 25), 'Christmas Day'), (datetime.date(2004, 12, 24), 'Christmas Day (observed)'), (datetime.date(2004, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2004, 2, 16), "Washington's Birthday"), (datetime.date(2004, 10, 11), 'Columbus Day'), (datetime.date(2004, 11, 11), 'Veterans Day'), (datetime.date(2005, 1, 1), "New Year's Day"), (datetime.date(2005, 5, 30), 'Memorial Day'), (datetime.date(2005, 7, 4), 'Independence Day'), (datetime.date(2005, 9, 5), 'Labor Day'), (datetime.date(2005, 11, 24), 'Thanksgiving Day'), (datetime.date(2005, 12, 25), 'Christmas Day'), (datetime.date(2005, 12, 26), 'Christmas Day (observed)'), (datetime.date(2005, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2005, 2, 21), "Washington's Birthday"), (datetime.date(2005, 10, 10), 'Columbus Day'), (datetime.date(2005, 11, 11), 'Veterans Day'), (datetime.date(2006, 1, 1), "New Year's Day"), (datetime.date(2006, 1, 2), "New Year's Day (observed)"), (datetime.date(2006, 5, 29), 'Memorial Day'), (datetime.date(2006, 7, 4), 'Independence Day'), (datetime.date(2006, 9, 4), 'Labor Day'), (datetime.date(2006, 11, 23), 'Thanksgiving Day'), (datetime.date(2006, 12, 25), 'Christmas Day'), (datetime.date(2006, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2006, 2, 20), "Washington's Birthday"), (datetime.date(2006, 10, 9), 'Columbus Day'), (datetime.date(2006, 11, 11), 'Veterans Day'), (datetime.date(2006, 11, 10), 'Veterans Day (observed)'), (datetime.date(2007, 1, 1), "New Year's Day"), (datetime.date(2007, 5, 28), 'Memorial Day'), (datetime.date(2007, 7, 4), 'Independence Day'), (datetime.date(2007, 9, 3), 'Labor Day'), (datetime.date(2007, 11, 22), 'Thanksgiving Day'), (datetime.date(2007, 12, 25), 'Christmas Day'), (datetime.date(2007, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2007, 2, 19), "Washington's Birthday"), (datetime.date(2007, 10, 8), 'Columbus Day'), (datetime.date(2007, 11, 11), 'Veterans Day'), (datetime.date(2007, 11, 12), 'Veterans Day (observed)'), (datetime.date(2008, 1, 1), "New Year's Day"), (datetime.date(2008, 5, 26), 'Memorial Day'), (datetime.date(2008, 7, 4), 'Independence Day'), (datetime.date(2008, 9, 1), 'Labor Day'), (datetime.date(2008, 11, 27), 'Thanksgiving Day'), (datetime.date(2008, 12, 25), 'Christmas Day'), (datetime.date(2008, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2008, 2, 18), "Washington's Birthday"), (datetime.date(2008, 10, 13), 'Columbus Day'), (datetime.date(2008, 11, 11), 'Veterans Day'), (datetime.date(2009, 1, 1), "New Year's Day"), (datetime.date(2009, 5, 25), 'Memorial Day'), (datetime.date(2009, 7, 4), 'Independence Day'), (datetime.date(2009, 7, 3), 'Independence Day (observed)'), (datetime.date(2009, 9, 7), 'Labor Day'), (datetime.date(2009, 11, 26), 'Thanksgiving Day'), (datetime.date(2009, 12, 25), 'Christmas Day'), (datetime.date(2009, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2009, 2, 16), "Washington's Birthday"), (datetime.date(2009, 10, 12), 'Columbus Day'), (datetime.date(2009, 11, 11), 'Veterans Day'), (datetime.date(2010, 1, 1), "New Year's Day"), (datetime.date(2010, 12, 31), "New Year's Day (observed)"), (datetime.date(2010, 5, 31), 'Memorial Day'), (datetime.date(2010, 7, 4), 'Independence Day'), (datetime.date(2010, 7, 5), 'Independence Day (observed)'), (datetime.date(2010, 9, 6), 'Labor Day'), (datetime.date(2010, 11, 25), 'Thanksgiving Day'), (datetime.date(2010, 12, 25), 'Christmas Day'), (datetime.date(2010, 12, 24), 'Christmas Day (observed)'), (datetime.date(2010, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2010, 2, 15), "Washington's Birthday"), (datetime.date(2010, 10, 11), 'Columbus Day'), (datetime.date(2010, 11, 11), 'Veterans Day'), (datetime.date(2011, 1, 1), "New Year's Day"), (datetime.date(2011, 5, 30), 'Memorial Day'), (datetime.date(2011, 7, 4), 'Independence Day'), (datetime.date(2011, 9, 5), 'Labor Day'), (datetime.date(2011, 11, 24), 'Thanksgiving Day'), (datetime.date(2011, 12, 25), 'Christmas Day'), (datetime.date(2011, 12, 26), 'Christmas Day (observed)'), (datetime.date(2011, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2011, 2, 21), "Washington's Birthday"), (datetime.date(2011, 10, 10), 'Columbus Day'), (datetime.date(2011, 11, 11), 'Veterans Day'), (datetime.date(2012, 1, 1), "New Year's Day"), (datetime.date(2012, 1, 2), "New Year's Day (observed)"), (datetime.date(2012, 5, 28), 'Memorial Day'), (datetime.date(2012, 7, 4), 'Independence Day'), (datetime.date(2012, 9, 3), 'Labor Day'), (datetime.date(2012, 11, 22), 'Thanksgiving Day'), (datetime.date(2012, 12, 25), 'Christmas Day'), (datetime.date(2012, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2012, 2, 20), "Washington's Birthday"), (datetime.date(2012, 10, 8), 'Columbus Day'), (datetime.date(2012, 11, 11), 'Veterans Day'), (datetime.date(2012, 11, 12), 'Veterans Day (observed)'), (datetime.date(2013, 1, 1), "New Year's Day"), (datetime.date(2013, 5, 27), 'Memorial Day'), (datetime.date(2013, 7, 4), 'Independence Day'), (datetime.date(2013, 9, 2), 'Labor Day'), (datetime.date(2013, 11, 28), 'Thanksgiving Day'), (datetime.date(2013, 12, 25), 'Christmas Day'), (datetime.date(2013, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2013, 2, 18), "Washington's Birthday"), (datetime.date(2013, 10, 14), 'Columbus Day'), (datetime.date(2013, 11, 11), 'Veterans Day'), (datetime.date(2014, 1, 1), "New Year's Day"), (datetime.date(2014, 5, 26), 'Memorial Day'), (datetime.date(2014, 7, 4), 'Independence Day'), (datetime.date(2014, 9, 1), 'Labor Day'), (datetime.date(2014, 11, 27), 'Thanksgiving Day'), (datetime.date(2014, 12, 25), 'Christmas Day'), (datetime.date(2014, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2014, 2, 17), "Washington's Birthday"), (datetime.date(2014, 10, 13), 'Columbus Day'), (datetime.date(2014, 11, 11), 'Veterans Day'), (datetime.date(2015, 1, 1), "New Year's Day"), (datetime.date(2015, 5, 25), 'Memorial Day'), (datetime.date(2015, 7, 4), 'Independence Day'), (datetime.date(2015, 7, 3), 'Independence Day (observed)'), (datetime.date(2015, 9, 7), 'Labor Day'), (datetime.date(2015, 11, 26), 'Thanksgiving Day'), (datetime.date(2015, 12, 25), 'Christmas Day'), (datetime.date(2015, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2015, 2, 16), "Washington's Birthday"), (datetime.date(2015, 10, 12), 'Columbus Day'), (datetime.date(2015, 11, 11), 'Veterans Day'), (datetime.date(2016, 1, 1), "New Year's Day"), (datetime.date(2016, 5, 30), 'Memorial Day'), (datetime.date(2016, 7, 4), 'Independence Day'), (datetime.date(2016, 9, 5), 'Labor Day'), (datetime.date(2016, 11, 24), 'Thanksgiving Day'), (datetime.date(2016, 12, 25), 'Christmas Day'), (datetime.date(2016, 12, 26), 'Christmas Day (observed)'), (datetime.date(2016, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2016, 2, 15), "Washington's Birthday"), (datetime.date(2016, 10, 10), 'Columbus Day'), (datetime.date(2016, 11, 11), 'Veterans Day'), (datetime.date(2017, 1, 1), "New Year's Day"), (datetime.date(2017, 1, 2), "New Year's Day (observed)"), (datetime.date(2017, 5, 29), 'Memorial Day'), (datetime.date(2017, 7, 4), 'Independence Day'), (datetime.date(2017, 9, 4), 'Labor Day'), (datetime.date(2017, 11, 23), 'Thanksgiving Day'), (datetime.date(2017, 12, 25), 'Christmas Day'), (datetime.date(2017, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2017, 2, 20), "Washington's Birthday"), (datetime.date(2017, 10, 9), 'Columbus Day'), (datetime.date(2017, 11, 11), 'Veterans Day'), (datetime.date(2017, 11, 10), 'Veterans Day (observed)'), (datetime.date(2018, 1, 1), "New Year's Day"), (datetime.date(2018, 5, 28), 'Memorial Day'), (datetime.date(2018, 7, 4), 'Independence Day'), (datetime.date(2018, 9, 3), 'Labor Day'), (datetime.date(2018, 11, 22), 'Thanksgiving Day'), (datetime.date(2018, 12, 25), 'Christmas Day'), (datetime.date(2018, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2018, 2, 19), "Washington's Birthday"), (datetime.date(2018, 10, 8), 'Columbus Day'), (datetime.date(2018, 11, 11), 'Veterans Day'), (datetime.date(2018, 11, 12), 'Veterans Day (observed)'), (datetime.date(2019, 1, 1), "New Year's Day"), (datetime.date(2019, 5, 27), 'Memorial Day'), (datetime.date(2019, 7, 4), 'Independence Day'), (datetime.date(2019, 9, 2), 'Labor Day'), (datetime.date(2019, 11, 28), 'Thanksgiving Day'), (datetime.date(2019, 12, 25), 'Christmas Day'), (datetime.date(2019, 1, 21), 'Martin Luther King Jr. Day'), (datetime.date(2019, 2, 18), "Washington's Birthday"), (datetime.date(2019, 10, 14), 'Columbus Day'), (datetime.date(2019, 11, 11), 'Veterans Day'), (datetime.date(2020, 1, 1), "New Year's Day"), (datetime.date(2020, 5, 25), 'Memorial Day'), (datetime.date(2020, 7, 4), 'Independence Day'), (datetime.date(2020, 7, 3), 'Independence Day (observed)'), (datetime.date(2020, 9, 7), 'Labor Day'), (datetime.date(2020, 11, 26), 'Thanksgiving Day'), (datetime.date(2020, 12, 25), 'Christmas Day'), (datetime.date(2020, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2020, 2, 17), "Washington's Birthday"), (datetime.date(2020, 10, 12), 'Columbus Day'), (datetime.date(2020, 11, 11), 'Veterans Day'), (datetime.date(2021, 1, 1), "New Year's Day"), (datetime.date(2021, 12, 31), "New Year's Day (observed)"), (datetime.date(2021, 5, 31), 'Memorial Day'), (datetime.date(2021, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2021, 6, 18), 'Juneteenth National Independence Day (observed)'), (datetime.date(2021, 7, 4), 'Independence Day'), (datetime.date(2021, 7, 5), 'Independence Day (observed)'), (datetime.date(2021, 9, 6), 'Labor Day'), (datetime.date(2021, 11, 25), 'Thanksgiving Day'), (datetime.date(2021, 12, 25), 'Christmas Day'), (datetime.date(2021, 12, 24), 'Christmas Day (observed)'), (datetime.date(2021, 1, 18), 'Martin Luther King Jr. Day'), (datetime.date(2021, 2, 15), "Washington's Birthday"), (datetime.date(2021, 10, 11), 'Columbus Day'), (datetime.date(2021, 11, 11), 'Veterans Day'), (datetime.date(2022, 1, 1), "New Year's Day"), (datetime.date(2022, 5, 30), 'Memorial Day'), (datetime.date(2022, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2022, 6, 20), 'Juneteenth National Independence Day (observed)'), (datetime.date(2022, 7, 4), 'Independence Day'), (datetime.date(2022, 9, 5), 'Labor Day'), (datetime.date(2022, 11, 24), 'Thanksgiving Day'), (datetime.date(2022, 12, 25), 'Christmas Day'), (datetime.date(2022, 12, 26), 'Christmas Day (observed)'), (datetime.date(2022, 1, 17), 'Martin Luther King Jr. Day'), (datetime.date(2022, 2, 21), "Washington's Birthday"), (datetime.date(2022, 10, 10), 'Columbus Day'), (datetime.date(2022, 11, 11), 'Veterans Day'), (datetime.date(2023, 1, 1), "New Year's Day"), (datetime.date(2023, 1, 2), "New Year's Day (observed)"), (datetime.date(2023, 5, 29), 'Memorial Day'), (datetime.date(2023, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2023, 7, 4), 'Independence Day'), (datetime.date(2023, 9, 4), 'Labor Day'), (datetime.date(2023, 11, 23), 'Thanksgiving Day'), (datetime.date(2023, 12, 25), 'Christmas Day'), (datetime.date(2023, 1, 16), 'Martin Luther King Jr. Day'), (datetime.date(2023, 2, 20), "Washington's Birthday"), (datetime.date(2023, 10, 9), 'Columbus Day'), (datetime.date(2023, 11, 11), 'Veterans Day'), (datetime.date(2023, 11, 10), 'Veterans Day (observed)'), (datetime.date(2024, 1, 1), "New Year's Day"), (datetime.date(2024, 5, 27), 'Memorial Day'), (datetime.date(2024, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2024, 7, 4), 'Independence Day'), (datetime.date(2024, 9, 2), 'Labor Day'), (datetime.date(2024, 11, 28), 'Thanksgiving Day'), (datetime.date(2024, 12, 25), 'Christmas Day'), (datetime.date(2024, 1, 15), 'Martin Luther King Jr. Day'), (datetime.date(2024, 2, 19), "Washington's Birthday"), (datetime.date(2024, 10, 14), 'Columbus Day'), (datetime.date(2024, 11, 11), 'Veterans Day'), (datetime.date(2025, 1, 1), "New Year's Day"), (datetime.date(2025, 5, 26), 'Memorial Day'), (datetime.date(2025, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2025, 7, 4), 'Independence Day'), (datetime.date(2025, 9, 1), 'Labor Day'), (datetime.date(2025, 11, 27), 'Thanksgiving Day'), (datetime.date(2025, 12, 25), 'Christmas Day'), (datetime.date(2025, 1, 20), 'Martin Luther King Jr. Day'), (datetime.date(2025, 2, 17), "Washington's Birthday"), (datetime.date(2025, 10, 13), 'Columbus Day'), (datetime.date(2025, 11, 11), 'Veterans Day'), (datetime.date(2026, 1, 1), "New Year's Day"), (datetime.date(2026, 5, 25), 'Memorial Day'), (datetime.date(2026, 6, 19), 'Juneteenth National Independence Day'), (datetime.date(2026, 7, 4), 'Independence Day'), (datetime.date(2026, 7, 3), 'Independence Day (observed)'), (datetime.date(2026, 9, 7), 'Labor Day'), (datetime.date(2026, 11, 26), 'Thanksgiving Day'), (datetime.date(2026, 12, 25), 'Christmas Day'), (datetime.date(2026, 1, 19), 'Martin Luther King Jr. Day'), (datetime.date(2026, 2, 16), "Washington's Birthday"), (datetime.date(2026, 10, 12), 'Columbus Day'), (datetime.date(2026, 11, 11), 'Veterans Day')]
       Datum
0 2000-09-02
1 2000-09-03
2 2000-09-09
3 2000-09-10
4 2000-09-16

In [ ]:
# TODO: Methode Reparieren.
# Zielbild alle Feiertage und Wochenenden in einem Dataframe und Daten sind korrekt aufsteigend sortiert.
# Anschließend mit Df (fehlende_tage_df)von Oben vergelichen ob dies alle fehlenden WErte erklärt.

df_weHol = pd.concat([feiertag_df,we_df])
df_weHol.drop(columns=['Name des Feiertags'], inplace=True)
#feiertag_df.size #614
#we_df.size #2700
df_weHol['Datum'] = pd.to_datetime(df_weHol['Datum'], errors='coerce').dt.floor('D')


df_weHol.drop_duplicates(inplace=True)
df_weHol.sort_values(by='Datum', ascending=True, inplace=True)
df_weHol_final = df_weHol.sort_values(by='Datum', ascending=True).reset_index(drop=True)
print(df_weHol_final['Datum'])

0      2000-01-01
1      2000-01-17
2      2000-02-21
3      2000-05-29
4      2000-07-04
          ...
2971   2026-09-07
2972   2026-10-12
2973   2026-11-11
2974   2026-11-26
2975   2026-12-25
Name: Datum, Length: 2976, dtype: datetime64[us]

In [ ]:
#Falsch
#dates_ref = pd.to_datetime(referenz_kalender['Date'], utc=True, errors='coerce')
#dates_dat = pd.to_datetime(df_prep['Date'], utc=True, errors='coerce')
dates_ref = pd.to_datetime(df_prep['Date'], utc=True, errors='coerce')
dates_dat = pd.to_datetime(df_weHol['Datum'], utc=True, errors='coerce')


set_referenz = set(dates_ref.dt.date.dropna())
set_daten = set(dates_dat.dt.date.dropna())

fehlende_tage_liste = sorted(list(set_referenz - set_daten))

# 4. Ergebnis zurück in ein sauberes DataFrame gießen
vergleichs_df = pd.DataFrame({'Datum': pd.to_datetime(fehlende_tage_liste)})

print("\nDie ersten fehlenden Tage:")
print(vergleichs_df.head(10))
print(vergleichs_df.size)

Die ersten fehlenden Tage:
       Datum
0 2000-09-01
1 2000-09-05
2 2000-09-06
3 2000-09-07
4 2000-09-08
5 2000-09-11
6 2000-09-12
7 2000-09-13
8 2000-09-14
9 2000-09-15
6431

In [36]:
## Erklärung für Ergebnisse finden.
missing_pd = fehlende_tage_df
#pd.DataFrame(fehlende_tage_lst, columns=["Datum"])

we_hol_set = set(pd.to_datetime(df_weHol["Datum"]).dt.strftime("%Y-%m-%d"))
missing_val_set = set(pd.to_datetime(missing_pd["Date"]).dt.strftime("%Y-%m-%d"))

# Vorhanden?
same = sorted(list(we_hol_set.intersection(missing_val_set)))

# Fehlend Weder Wochenende noch Feiertag
missing_1 = sorted(list(missing_val_set - we_hol_set))

# Fehlend Wochenende oder Feiertag
missing_2 = sorted(list(we_hol_set - missing_val_set))

print("1. Anzahl identischen Daten in beiden Listen vorhanden:", len(same), same)
print("2. Anzahl und Werte die fehlen im Wochende/Feiertag:",len(missing_1), missing_1)
print("3. Anzahl und Werte, welche weder Wochenende noch Feiertag sind:",len(missing_2), missing_2)

KeyError: 'Date'

In [ ]:
#Daten ohne Leerzeichen speichern.
df_prep.to_csv("../Data/goldpreis_seit_2000_prep.csv")

In [ ]:
# Schlusskurs des Tages als Preis nutzen.
w = df_prep['Close'].tolist()
print(w)

In [ ]:
# Erste 10 Tage visualisieren zu denen wir Werte haben
w2 = w[0:10]
print(w2)

In [ ]:
# Schlusskurs des Tages als Preis nutzen.
date_d = df_prep['Date'].tolist()
print(date_d)

In [ ]:
date_d_first30 = date_d[0:10]
print(date_d_first30)

In [ ]:
# Goldkurs visualisieren
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.dates as mdates
import warnings

# Data for plotting
w = w2
start_date = pd.to_datetime("2000-09-01")
end_date = pd.to_datetime("2026-07-12")
full_time_range = pd.date_range(start=start_date, end=end_date, freq='d')
t = date_d_first30

fig, ax = plt.subplots()
ax.plot(t, w)

# Versuch...
for tag in pd.date_range(start=df.index.min(), end=df.index.max(), freq="D"):
    if tag.weekday() in [5, 6] or tag in feiertage:
        # Berechne Start und Ende des Tages für die exakte Blockbreite
        start = tag - pd.Timedelta(hours=12)
        ende = tag + pd.Timedelta(hours=12)
        
        # Vertikalen Hintergrund-Block zeichnen
        ax.axvspan(start, ende, color="lightgray", alpha=0.5, label="Keine Daten" if "Keine Daten" not in ax.get_legend_handles_labels()[1] else "")

        
 
ax.set(xlabel='Tag (t)', ylabel='Kurs (w)',
       title='Goldkurs seit erste 30 Tage') 

# Rotieren der X-Achsen-Beschriftung, damit sich die Datumsangaben nicht überschneiden
plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
ax.xaxis.set_major_locator(mdates.DayLocator(interval=1))        
ax.grid()

fig.savefig("test.png")
plt.show()

In [ ]:
# Goldkurs visualisieren
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.dates as mdates
import warnings

# Data for plotting
w = df['Price'].tolist()
start_date = pd.to_datetime("2000-09-01")
end_date = pd.to_datetime("2026-07-12")
full_time_range = pd.date_range(start=start_date, end=end_date, freq='d')
t = full_time_range
fig, ax = plt.subplots()
ax.plot(w, t)

ax.set(xlabel='Tag (t)', ylabel='Kurs (w)',
       title='Goldkurs seit 09/2000')
ax.grid()

fig.savefig("test.png")
plt.show()